# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb903caa20623b5608c4acc5ea3c4879a5b60376eac3a5954882963e6ae78769e78794b2239e654446aa688ec428e23bf355f0ad4a7c02ed2072492566385dd7

test:
  secret_key_base: 91f4e68090c9896a10cf0ac040c82408a9982e9f49767af8df2e2a1af22b4a8355d72676a985a4230e54731fbc6c57fdd934fba7de15f206a197f7a7fac6882b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
